### ISSUE TITLE
Some issues of design

### ISSUE THREAD

**Issue by aslozada** [awvwgk/fpm-docs#16]
* The title block doesn't work in awvwgk.github.io/fpm-docs/

en/index.html
![en](https://user-images.githubusercontent.com/3170541/144707801-06ab8256-ef5a-45d4-ad23-db4a4ab83121.png)
de/index.html
![de](https://user-images.githubusercontent.com/3170541/144707815-6dce5dc9-fb44-4a8b-838a-adce989ab5e9.png)
zh_CN/index.html
![cn](https://user-images.githubusercontent.com/3170541/144707857-a159a9f7-fd09-4c52-9389-4bb59987c138.png)
es/index.html
![es](https://user-images.githubusercontent.com/3170541/144707957-7e956bdd-c4d2-4f62-8278-f807aa45b4af.png)

* The language links only work on the page index.html.

**Comment by awvwgk** [comment]
It shows up for me, which browser are you using?

**Comment by aslozada** [comment]
Google Chrome Version 95.0.4638.69 (Official Build) (64-bit) 
* title block  (doesn't work)
* language links (doesn't work, except in ```index.html```)

Mozilla Firefox 93.0 
* title block (Ok!)
*  language links (doesn't work, except in ```index.html```)

**Comment by awvwgk** [comment]
I fixed the language navigation. Can reproduce the missing style for the title block, maybe I just use a bootstrap card instead of creating it directly in CSS.

**Comment by aslozada** [comment]
other tests

on Windows 10
Firefox Version 94.0.2 (64-bit)
* title block (Ok!)

Google Chrome Version 96.0.4664.46 (build 64-bit)  
* title block (doesn't work)

Microsoft Edge Version 96.01054.41 (64-bit) 
* title block (doesn't work)
------

on Android 7.12
Chrome Version 95.0.4638.74
* title block (doesn't work)

**Comment by awvwgk** [comment]
I switched to a bootstrap card now, I don't think the background gradient did add much value.
